import PDFDocument from 'pdfkit';
import type { DiffResult } from './diff-calculator.utils.js';

interface DiffPdfOptions {
  articleTitle: string;
  versionFrom: number;
  versionTo: number;
  editorName?: string;
  generatedBy: string;
}


export async function generateDiffPdf(
  diffData: DiffResult,
  options: DiffPdfOptions
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      // Create PDF document
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50,
        bufferPages: true,
      });

      const chunks: Buffer[] = [];

      // Collect data chunks
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      let yPosition = 50;

      // ===== HEADER SECTION =====
      doc.fontSize(24).font('Helvetica-Bold').fillColor('#2c3e50');
      doc.text('Article Diff Report', 50, yPosition);
      yPosition += 35;

      doc.fontSize(14).font('Helvetica').fillColor('#34495e');
      doc.text(options.articleTitle, 50, yPosition, { width: 500 });
      yPosition += 25;

      doc.fontSize(11).fillColor('#7f8c8d');
      doc.text(`Version ${options.versionFrom} → Version ${options.versionTo}`, 50, yPosition);
      yPosition += 15;

      if (options.editorName) {
        doc.text(`Edited by: ${options.editorName}`, 50, yPosition);
        yPosition += 15;
      }

      doc.text(`Generated: ${new Date().toLocaleString()}`, 50, yPosition);
      yPosition += 15;
      doc.text(`Generated by: ${options.generatedBy}`, 50, yPosition);
      yPosition += 20;

      // Draw separator line
      doc.moveTo(50, yPosition).lineTo(550, yPosition).strokeColor('#bdc3c7').stroke();
      yPosition += 25;

      // ===== SUMMARY SECTION =====
      doc.fontSize(16).font('Helvetica-Bold').fillColor('#2c3e50');
      doc.text('Summary', 50, yPosition);
      yPosition += 25;

      doc.fontSize(12).font('Helvetica');

      // Added lines
      doc.fillColor('#27ae60');
      doc.text(`✓ ${diffData.summary.totalAdded} lines added`, 70, yPosition);
      yPosition += 20;

      // Removed lines
      doc.fillColor('#e74c3c');
      doc.text(`✗ ${diffData.summary.totalRemoved} lines removed`, 70, yPosition);
      yPosition += 20;

      // Modified lines
      doc.fillColor('#f39c12');
      doc.text(`⟳ ${diffData.summary.totalModified} lines modified`, 70, yPosition);
      yPosition += 20;

      // Unchanged lines
      doc.fillColor('#95a5a6');
      doc.text(`= ${diffData.summary.totalUnchanged} lines unchanged`, 70, yPosition);
      yPosition += 30;

      // Draw separator line
      doc.moveTo(50, yPosition).lineTo(550, yPosition).strokeColor('#bdc3c7').stroke();
      yPosition += 25;

      // ===== DETAILED CHANGES SECTION =====
      doc.fontSize(16).font('Helvetica-Bold').fillColor('#2c3e50');
      doc.text('Detailed Changes', 50, yPosition);
      yPosition += 25;

      doc.fontSize(9).font('Courier');

      // Helper function to check if new page is needed
      const checkNewPage = (requiredSpace: number = 25) => {
        if (yPosition > 750) {
          doc.addPage();
          yPosition = 50;
        }
      };

      // Draw removed lines
      if (diffData.removed.length > 0) {
        diffData.removed.forEach((line) => {
          checkNewPage();

          // Draw red background
          doc.rect(45, yPosition - 3, 510, 16)
            .fillAndStroke('#ffebee', '#ef5350')
            .fillColor('#c62828');

          // Draw text
          const text = `- Line ${line.oldLineNumber}: ${line.content}`;
          doc.text(text, 50, yPosition, { width: 500, ellipsis: true });
          yPosition += 18;
        });
      }

      // Draw added lines
      if (diffData.added.length > 0) {
        diffData.added.forEach((line) => {
          checkNewPage();

          // Draw green background
          doc.rect(45, yPosition - 3, 510, 16)
            .fillAndStroke('#e8f5e9', '#66bb6a')
            .fillColor('#2e7d32');

          // Draw text
          const text = `+ Line ${line.newLineNumber}: ${line.content}`;
          doc.text(text, 50, yPosition, { width: 500, ellipsis: true });
          yPosition += 18;
        });
      }

      // Draw modified lines
      if (diffData.modified.length > 0) {
        diffData.modified.forEach((line) => {
          checkNewPage(40);

          // Draw yellow background for both lines
          doc.rect(45, yPosition - 3, 510, 32)
            .fillAndStroke('#fff9e6', '#ffa726')
            .fillColor('#e65100');

          // Draw old line
          const oldText = `~ Line ${line.oldLineNumber}: ${line.content}`;
          doc.text(oldText, 50, yPosition, { width: 500, ellipsis: true });
          yPosition += 16;

          // Draw new line with arrow
          const newText = `  → ${line.content}`;
          doc.text(newText, 50, yPosition, { width: 500, ellipsis: true });
          yPosition += 20;
        });
      }

      // If no changes
      if (diffData.removed.length === 0 && 
          diffData.added.length === 0 && 
          diffData.modified.length === 0) {
        doc.fillColor('#95a5a6');
        doc.text('No changes detected between versions.', 50, yPosition);
      }

      // ===== FOOTER SECTION =====
      const pageCount = doc.bufferedPageRange().count;
      for (let i = 0; i < pageCount; i++) {
        doc.switchToPage(i);
        
        // Draw footer line
        doc.moveTo(50, 792 - 40).lineTo(550, 792 - 40).strokeColor('#bdc3c7').stroke();
        
        // Draw footer text
        doc.fontSize(8).fillColor('#95a5a6').font('Helvetica');
        doc.text(
          `Law Nation - Diff Report | Page ${i + 1} of ${pageCount}`,
          50,
          792 - 30,
          { align: 'center', width: 500 }
        );
      }

      // Finalize PDF
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Generate a simple text-based diff (fallback)
 */
export function generateDiffText(diffData: DiffResult): string {
  let text = '=== DIFF REPORT ===\n\n';
  
  text += 'SUMMARY:\n';
  text += `  Added: ${diffData.summary.totalAdded} lines\n`;
  text += `  Removed: ${diffData.summary.totalRemoved} lines\n`;
  text += `  Modified: ${diffData.summary.totalModified} lines\n`;
  text += `  Unchanged: ${diffData.summary.totalUnchanged} lines\n\n`;
  
  text += 'CHANGES:\n\n';
  
  diffData.removed.forEach(line => {
    text += `- Line ${line.oldLineNumber}: ${line.content}\n`;
  });
  
  diffData.added.forEach(line => {
    text += `+ Line ${line.newLineNumber}: ${line.content}\n`;
  });
  
  diffData.modified.forEach(line => {
    text += `~ Line ${line.oldLineNumber}: ${line.content}\n`;
    text += `  → ${line.content}\n`;
  });
  
  return text;
}
